"""Add status to group_members

Revision ID: 365d430d9498
Revises: e68477088bc9
Create Date: 2026-06-23 15:54:09.464184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365d430d9498'
down_revision = 'e68477088bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
