"""rename RoleGlobal to OrganizationRole (roles_global -> organization_roles)

Revision ID: 4fc4d2c8f250
Revises: bacbfccf49d2
Create Date: 2026-09-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc4d2c8f250'
down_revision = 'bacbfccf49d2'
branch_labels = None
depends_on = None


def upgrade():
    # Plain rename_table / alter_column (not autogenerated): PostgreSQL tracks
    # tables, columns, and FK constraints by internal OID, not by name, so a
    # rename here preserves all existing data and foreign keys pointing at
    # roles_global.id (organization_members.role_id, invitations.role_id)
    # without any further changes.
    op.rename_table('roles_global', 'organization_roles')
    op.rename_table('role_global_permissions', 'organization_role_permissions')
    op.alter_column(
        'organization_role_permissions',
        'role_global_id',
        new_column_name='organization_role_id',
    )


def downgrade():
    op.alter_column(
        'organization_role_permissions',
        'organization_role_id',
        new_column_name='role_global_id',
    )
    op.rename_table('organization_role_permissions', 'role_global_permissions')
    op.rename_table('organization_roles', 'roles_global')
