"""Add tokens_valid_after to users for JWT revocation

Revision ID: a262370839af
Revises: f2e6723a3e2c
Create Date: 2026-09-13 16:45:30.668918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a262370839af'
down_revision = 'f2e6723a3e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_valid_after', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tokens_valid_after')

    # ### end Alembic commands ###
