"""rename RoleLocal to GroupRole (roles_local -> group_roles)

Revision ID: f2e6723a3e2c
Revises: 4fc4d2c8f250
Create Date: 2026-09-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e6723a3e2c'
down_revision = '4fc4d2c8f250'
branch_labels = None
depends_on = None


def upgrade():
    # Plain rename_table / alter_column (not autogenerated): PostgreSQL tracks
    # tables, columns, and FK constraints by internal OID, not by name, so a
    # rename here preserves all existing data and the FK from
    # group_members.role_id pointing at roles_local.id without any further
    # changes.
    op.rename_table('roles_local', 'group_roles')
    op.rename_table('role_local_permissions', 'group_role_permissions')
    op.alter_column(
        'group_role_permissions',
        'role_local_id',
        new_column_name='group_role_id',
    )


def downgrade():
    op.alter_column(
        'group_role_permissions',
        'group_role_id',
        new_column_name='role_local_id',
    )
    op.rename_table('group_role_permissions', 'role_local_permissions')
    op.rename_table('group_roles', 'roles_local')
